### ISSUE TITLE
Missing function for number of lanes

### ISSUE THREAD

**Issue by mulimoen** [rust-lang/portable-simd#151]
One of my projects is currently using `packed_simd`, and uses a compile-time feature flag to choose a vector size. I tried porting this to `stdsimd`, which worked perfectly, apart from a missing function, to get the current number of lanes for a given simd type. `packed_simd` has the const fn [`lanes`](https://rust-lang.github.io/packed_simd/packed_simd_2/struct.Simd.html#method.lanes) which I used in this context. It would be great to have this also exposed for all types in this crate, and it should be rather trivial to implement.

Edit: It seems the trait item T::LANES is available, but this is awkward to find  in the documentation, and requires the `Vector` trait to be in scope. I am not sure whether adding the `lanes()` function is worth it for the ease of documentation.

**Comment by calebzulawski** [comment]
You may use the `Vector::LANES` and `Mask::LANES` trait consts to get the lane count of a type.

**Comment by calebzulawski** [comment]
Whoops--just saw your edit.  You can also do `<T as Vector>::LANES` if you dont want to pull it into scope.

**Comment by mulimoen** [comment]
Thanks @calebzulawski, this should suffice for my use case. I suppose `LANES` is rather obvious in hindsight, maybe this issue could be closed?

**Comment by mulimoen** [comment]
With the latest master we no longer have the `Vector` trait and no function to get the lane count. This issue should be reopened

**Comment by calebzulawski** [comment]
It's questionable to me how necessary this is now, since to have a generic vector you must already have a generic parameter for the lane count, and you could just use that parameter.

**Comment by Lokathor** [comment]
It's probably good just for docs and usability. Even with const generics, people largely expect to access things via methods rather than associated consts.

**Comment by mulimoen** [comment]
It makes the code more local as one does not have to chase down which `LANES` is applicable for which item when using items of differing sizes
