### ISSUE TITLE
Document internal unsafety

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/portable-simd#173]
Currently, we document public `unsafe fn` and their invariants.

However, as a highly `unsafe` crate, we should also document internally that we are maintaining invariants for `unsafe` blocks internally. That said, we are also so `unsafe` because almost everything is a thin wainscotting over `extern "platform-intrinsic"` calls. Those are **not** the focus of this issue. Rather, what we really want to document is anything that **isn't** just a straight pass-through to an internal `unsafe fn` intrinsic. These comments need not be publically exposed.

A few of these were surfaced in https://github.com/rust-lang/portable-simd/pull/172/files. Mostly, it's things like our internal implementation of existing trait-level `unsafe fn`. Also we should probably document the safety invariants on the `impl` too, not just on the trait.

**Comment by calebzulawski** [comment]
I started implementing this, but found an ICE in clippy: https://github.com/rust-lang/rust-clippy/issues/7934

**Comment by calebzulawski** [comment]
I think this is basically complete in the `feature/unsafety` branch, but I'll wait for a fix to the clippy lint so we can keep it up to date with CI.
