### ISSUE TITLE
The meaning of rotate_left/right

### ISSUE THREAD

**Issue by nixberg** [rust-lang/portable-simd#180]
Switching a project from `packed_simd_2` to `simd_core`, I noticed that [`rotate_left`](https://rust-lang.github.io/portable-simd/core_simd/simd/struct.Simd.html#method.rotate_left) and [`rotate_right`](https://rust-lang.github.io/portable-simd/core_simd/simd/struct.Simd.html#method.rotate_right) have [become](https://docs.rs/packed_simd_2/0.3.6/packed_simd_2/type.u32x4.html#method.rotate_left) horizontal operations, borrowing from [`std::slice`](https://doc.rust-lang.org/std/primitive.slice.html#method.rotate_left).

I believe this to be inconsistent and surprising

- since I consider SIMD types arithmetic types first,
- since `rotate_left` is (conceptually) just `(x << n) | (x >> (BITS - n))` and these constituent operations remain vertical,
- since [`rotate_left`](https://doc.rust-lang.org/std/primitive.u32.html#method.rotate_left)/[`right`](https://doc.rust-lang.org/std/primitive.u32.html#method.rotate_right) already exist in `std` as (trivially) vertical operations.

Also, there is precedent for `horizontal_` operations but not for explicitly vertical ones.

Therefore, whether or not `simd_core` ends up providing vertical rotation, I propose renaming the methods in question to something like `horizontal_rotate_left`.

**Comment by calebzulawski** [comment]
Relevant discussion: https://github.com/rust-lang/portable-simd/issues/14#issuecomment-701707241
