### ISSUE TITLE
impl `TryFrom<&[T]>` for Simd?

### ISSUE THREAD

**Issue by pro465** [rust-lang/portable-simd#194]
now that we have added `Simd::from_slice` (see #177), which panics when the len is not enough to construct the Simd; I think we may need to consider adding a `TryFrom` impl to let the users handle errors in case the conversion fails.

**Comment by workingjubilee** [comment]
I hesitate to add a conflict for `TryInto` from the appropriate reflexive impl.

**Comment by pro465** [comment]
@workingjubilee I'm confused. how would that potientially conflict? could you please show me a concrete example?

**Comment by thomcc** [comment]
Hm, I think given that it TryFrom => array exists for slices (and mut slices), that TryFrom makes sense here. Is there a reason you'd expect it to conflict? I also think people expect From/TryFrom conflicts, so they don't write code succeptable to it in the same way as e.g. arithmetic operators.

**Comment by pro465** [comment]
@workingjubilee hello? did you forget what & why you expected it to conflict?
