### ISSUE TITLE
`generic_const_exprs` feature not enabled when include in stdlib.

### ISSUE THREAD

**Issue by thomcc** [rust-lang/portable-simd#204]
Some APIs are gated behind `cfg(feature = "generic_const_exprs")`. When included in libcore, we're referenced by path, which means these are not enabled.

Notably, this means we don't have the `Mask` to/from bitmask conversions. There isn't really a great workaround for them either, and without it, there's... a great deal of `core::arch` code that can't be ported to portable-simd, since there's no equivalent to movemask beyond manual conversion (which does not seem to vectorize, and would suck to need to do manually regardless).

Sorry if this is already known and discussed elsewhere. I didn't see anything when searching for `generic_const_exprs`.

**Comment by workingjubilee** [comment]
At the moment, `#![feature(generic_const_exprs)]` is not allowed in `core` because it's an "incomplete feature" and `core` does not want to endure compiler crashes. We may need to reconsider our current implementation approach.

**Comment by calebzulawski** [comment]
One possibility would be a trait like `Bitmask<N>`, which could be implemented for both integers and arrays of u8.  That might solve the short term feature problem, but also solve the problem where many people are looking for integers and don't expect an array.

**Comment by calebzulawski** [comment]
(or inverting that trait as `ToBits<{int}> for Mask<...>`)

**Comment by saglam** [comment]
Is there a workaround to this at the moment, potentially by recompiling the stdlib? When I enable the `generic_const_exprs` for the entire corelib, `array` module fails to compile.

To be clear, I just need a way to use the `to_bitmask()` on the mask SIMD types.
