### ISSUE TITLE
[QUESTION] what do the simd cmp intrinsics lower to?

### ISSUE THREAD

**Issue by pro465** [rust-lang/portable-simd#208]
https://github.com/rust-lang/portable-simd/blob/master/crates/core_simd/src/intrinsics.rs#L49-L54

they didn't have any comments explaining what specific LLVM instruction they get lowered to, and i also couldn't find any instruction on the LLVM reference that closely resembled them

**Comment by bjorn3** [comment]
They get lowered to the `icmp` or `fcmp` llvm instruction depending on the lane type: https://github.com/rust-lang/rust/blob/1c0ed0d4c4bd7b39299966e57806d29ce38c95af/compiler/rustc_codegen_ssa/src/base.rs#L98-L124

**Comment by calebzulawski** [comment]
It's worth noting that there are no guarantees as to what anything lowers to--the only guarantee is that a function will perform the operation defined in its documentation, and do it relatively efficiently.

**Comment by Lokathor** [comment]
However please note that the entire portable-simd project is "best effort" in terms of giving a specific instruction.

We guarantee that the comparison will happen (and produce correct outputs) at a logical level, but the *exact* hardware path that happens is not intended to be guaranteed.

**Comment by pro465** [comment]
@Lokathor @bjorn3 @calebzulawski 

thank you all very much for your helpful analswers. i however, didnt understand anything about the code that @bjorn3 pointed to. does it just sign-extend `<N x i1>` to whatever the return type is? if so, calling `intinsics::simd_eq::<Simd<_, _>, bool` should not work, right?

**Comment by bjorn3** [comment]
In LLVM `i1` is the type for booleans.

**Comment by pro465** [comment]
@bjorn3 oh so, is calling `instrinsics::<Simd<N, _>, [bool; N]>` fine?

**Comment by pro465** [comment]
ok lemme try

**Comment by pro465** [comment]
@bjorn3 didn't work :(

https://github.com/pro465/portable-simd/runs/4429119312?check_suite_focus=true

**Comment by bjorn3** [comment]
Looks like cg_llvm explicitly checks that the return type is an integer vector: https://github.com/rust-lang/rust/blob/1c0ed0d4c4bd7b39299966e57806d29ce38c95af/compiler/rustc_codegen_llvm/src/intrinsic.rs#L907 Maybe `intrinsics::simd_eq::<Self, [u8; LANES]>(*self, *other) == [255; LANES]` works? Or I think even better `intrinsics::simd_reduce_all(intrinsics::simd_eq::<Self, [u8; LANES]>(*self, *other))`.

**Comment by pro465** [comment]
@bjorn3 still didnt work :(

**Comment by pro465** [comment]
@bjorn3 i think the error is coming from https://github.com/rust-lang/rust/blob/1c0ed0d4c4bd7b39299966e57806d29ce38c95af/compiler/rustc_codegen_llvm/src/intrinsic.rs#L894

which types have `is_simd()` return true?

**Comment by bjorn3** [comment]
`is_simd()` is true for any type with `#[repr(simd)]`. Of course. It needs to be `intrinsics::simd_reduce_all(intrinsics::simd_eq::<Self, Simd<u8, LANES>>(*self, *other))`. (`Simd<u8, LANES>` instead of `[u8; LANES]`)

**Comment by pro465** [comment]
now that makes sense, thank you!

**Comment by pro465** [comment]
finally compiled! thank you all, just waiting all tests to pass and then i will close this issue 😄
