### ISSUE TITLE
Request: Shift by Immediate

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/portable-simd#214]
It should be possible to bit shift by an immediate value, using const generics. This doesn't seem to be in the API at the moment.

**Comment by programmerjake** [comment]
I'd expect:
```rust
x << Simd::splat(5)
```
to always trivially const-propagate when llvm is doing any inlining, which gives exactly the same IR as you'd get from any shift-by-immediate operators one could add...

Therefore, I think adding special shift-by-immediate operators isn't really necessary.

**Comment by programmerjake** [comment]
assuming this request was inspired by `swizzle`, `swizzle` is different because the corresponding LLVM IR instruction is only valid with a constant swizzle argument, unlike shifting.

**Comment by Lokathor** [comment]
Well the request was inspired by  `_mm256_slli_epi32` vs `_mm256_sllv_epi32`

Though, a [quick godbolt](https://rust.godbolt.org/z/31a9brs7c) shows that it does indeed seem to just const prop as intended when we go through IR instead of specific llvm functions like stdarch does.

**Comment by thomcc** [comment]
It doesn't with `-Copt-level=s` or `-Copt-level=z`.

Nearly every production use of Rust code (outside of serverside or distribution in places like Linux package repos) I've seen in my career has used one of these, but we seem to have... larger issue from here, judging by everything else I see in the godbolt :(

**Comment by calebzulawski** [comment]
I think optimizing for size with SIMD is probably not reasonable, especially a portable implementation that inherently relies on speed optimizations.

**Comment by thomcc** [comment]
People optimize for size as it's the difference between a very large executable and a small one — it's not about a consideration of "does this use SIMD or not", it's "I'd rather not ship a 7MB binary when the C++ one was 1MB" (which yes, ignores the statically linked standard library, but still is the thought process people are using when choosing these compilation options)

**Comment by calebzulawski** [comment]
Perhaps this is a good use case for per-function optimization etc

**Comment by programmerjake** [comment]
i'd say this is a good use case for `inline(always)` cuz the call overhead is basically always more expensive than the simd ops...

**Comment by thomcc** [comment]
Yeah, that's probably true of a lot of functions in core::simd as well.

**Comment by programmerjake** [comment]
if a shift doesn't compile to an inlined splat and simd shift, even with optimizing for size, then there's something wrong with our implementation imho

**Comment by calebzulawski** [comment]
My understanding is that `inline(always)` is now identical to `inline`

**Comment by thomcc** [comment]
What? When did that happen?

**Comment by calebzulawski** [comment]
I think as long as you are using at least ThinLTO, it's identical.

**Comment by bjorn3** [comment]
LLVM uses a different inline threshold for `InlineHint` (`#[inline]`) and `AlwaysInline` (`#[inline(always)]`): https://github.com/llvm/llvm-project/blob/feb40a3a475c1f87182f991409f4b77176415c9b/llvm/lib/Analysis/InlineCost.cpp#L3022-L3032 Also according to https://github.com/llvm/llvm-project/blob/feb40a3a475c1f87182f991409f4b77176415c9b/llvm/lib/Analysis/InlineCost.cpp#L2865-L2872 inlining should happen whenever possible for `AlwaysInline`.

**Comment by Lokathor** [comment]
I think slightly separately, if llvm doesn't inline a const expression and produce the right instruction with the current code (because of a lower inline level), then there's not much reason to think that a dedicated function using const generics would do better. If they're both going to end up becoming the same Llvm Ir.
