### ISSUE TITLE
Any plans for implementing `mul_hi` ?

### ISSUE THREAD

**Issue by itzmeanjan** [rust-lang/portable-simd#220]
Hello,

I was looking for `mul_hi` function ( like in OpenCL https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#integer-functions , search for `mul_hi` ), but didn't find one. For now I've implemented one, which solves my problem, but I wonder if there's any plan of implementing that. 

For reference, my current ( naive ) implementation of `mul_hi` looks like https://github.com/itzmeanjan/simd-rescue-prime/blob/c2b4de00c3809a7cd1ca6ae2e567d740be4b4881/src/ff.rs#L10-L25 --- if you have any comment on improving that, you're welcome. 

Thanks

**Comment by workingjubilee** [comment]
Possibly not. But we will add functions for casting a vector of integers to a vector of integers with a wider size and then using that as a basic "primitive" for `mul_hi`, and that consistently optimizes. We may consider the `widening_mul` integers are currently experimenting with, or maybe not.

**Comment by itzmeanjan** [comment]
Ok, thanks @workingjubilee
