### ISSUE TITLE
Reasoning behind the trait-oriented design

### ISSUE THREAD

**Issue by Urgau** [rust-lang/portable-simd#230]
Hi, I was wondering why this crate choose to go with a **trait-oriented design** and all the complication with it **instead** of going with the **primitive/struct and macros route** like core is doing for `uX`, `iX` and `fX` ?

**Comment by workingjubilee** [comment]
Apologies, but it's best if conversation about this is contained in a single issue. Answered in https://github.com/rust-lang/portable-simd/issues/228#issuecomment-1019352921
