### ISSUE TITLE
clean up `round_from_int` and `to_int_unchecked` after #232

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/portable-simd#233]
you could remove `round_from_int` afaict because it's functionality is completely supplanted by `cast`

also `to_int_unchecked` should be generic over return type

_Originally posted by @programmerjake in https://github.com/rust-lang/portable-simd/issues/232#issuecomment-1022865934_

**Comment by programmerjake** [comment]
Yes, I was thinking "hm, do I want to touch `fn round_from_int`?" but then I realized I didn't have a good vibe anymore for how strong the consensus was around `fn round_from_int` and `fn to_int_unchecked`, so I was going to bring that up at our next sync.

_Originally posted by @workingjubilee in https://github.com/rust-lang/portable-simd/issues/232#issuecomment-1022875974_

**Comment by workingjubilee** [comment]
Probably! `Simd::cast` is effectively a lanewise version of Rust's `as`, which means that for floats, it does a saturating conversion to the integer. Sight unseen, you may want to, for peeling out data, use `Simd<f32>::{from,to}_bits` instead.

**Comment by andy-thomason** [comment]
That is great as I'm translating scalar expressions to SIMD. Having something which is directly like `as` would be ideal.

The code is quite crude at the moment, but does produce a working translation.
