### ISSUE TITLE
Redundant register-to-register moves before register shuffle in SSE

### ISSUE THREAD

**Issue by ZhennanWu** [rust-lang/portable-simd#254]
The full example is available at: https://godbolt.org/z/vdzP6z8WY

First of all, thank you for your marvellous work at portable-simd. I'm a new learner therefore was not sure whether this is an LLVM problem or not. But the following sub-optimal code generation pattern was repetitively observed in a 4x4 matrix multiplication:

Example code

```rust
pub struct Matrix4 {
    // Column-major
    elems: [f32; 16],
}

impl Matrix4 {
    fn mul_mat_simd_128(self, rhs: Self) -> Self {
        let lhs_cols: [f32x4; 4] = unsafe { std::mem::transmute(self.elems) };
        let rhs_cols: [f32x4; 4] = unsafe { std::mem::transmute(rhs.elems) };
        let mut res: [f32x4; 4] = Default::default();
        for j in 0..4usize {
            let c = rhs_cols[j]; // This manual invariant extraction is necessary. Otherwise it will load from memory instead of xmm.
            res[j] = lhs_cols[0] * f32x4::from([c[0]; 4]);
            for k in 1..4usize {
                res[j] += lhs_cols[k] * f32x4::from([c[k]; 4]);
            }
        }
        return Matrix4 {
            elems: unsafe { std::mem::transmute(res) },
        };
    }
}
```

The generated assembly under `-C opt-level=3 -C lto=on -C panic=abort -C target_cpu=x86-64-v2`

```asm
<example::Matrix4 as core::ops::arith::Mul>::mul:
        mov     rax, rdi
        movups  xmm7, xmmword ptr [rsi]
        movups  xmm6, xmmword ptr [rsi + 16]
        movups  xmm9, xmmword ptr [rsi + 32]
        movups  xmm8, xmmword ptr [rsi + 48]
        movups  xmm5, xmmword ptr [rdx]
        movups  xmm1, xmmword ptr [rdx + 16]
        movups  xmm2, xmmword ptr [rdx + 32]
        movups  xmm3, xmmword ptr [rdx + 48]
        movaps  xmm0, xmm5
        shufps  xmm0, xmm5, 0
        mulps   xmm0, xmm7
        movaps  xmm4, xmm5
        shufps  xmm4, xmm5, 85
        mulps   xmm4, xmm6
        addps   xmm4, xmm0
        movaps  xmm0, xmm5
        shufps  xmm0, xmm5, 170
        mulps   xmm0, xmm9
        addps   xmm0, xmm4
        shufps  xmm5, xmm5, 255
        mulps   xmm5, xmm8
        addps   xmm5, xmm0
        movaps  xmm0, xmm1
        shufps  xmm0, xmm1, 0
        mulps   xmm0, xmm7
        movaps  xmm4, xmm1
        shufps  xmm4, xmm1, 85
//..................
```

As can be seen, before each `shufps` there is a `movaps` between the exact same set of `xmm` registers. According to my understanding, this shouldn't be necessary. Whatever was moved into the `xmm` will be immediately overwritten by `shufps` ([Reference](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=shufps&ig_expand=6426))

This pattern may well be caused by other stuff on the toolchain. But I will report it here for now.

### Meta

`rustc --version --verbose`:
```
Full compiler version
rustc 1.61.0-nightly (4ce374923 2022-02-28)
```

### Related information
1. This pattern disppears under `target_feature=+avx2` or `target_feature=+avx512f`
2. If the manual loop-invariant extraction in the example was disabled, we will see the following generated asms:
```asm
<example::Matrix4 as core::ops::arith::Mul>::mul:
        mov     rax, rdi
        movups  xmm4, xmmword ptr [rsi]
        movups  xmm3, xmmword ptr [rsi + 16]
        movups  xmm2, xmmword ptr [rsi + 32]
        movups  xmm8, xmmword ptr [rsi + 48]
        movups  xmm5, xmmword ptr [rdx]
        movups  xmm6, xmmword ptr [rdx + 4]
        movups  xmm7, xmmword ptr [rdx + 8]
        movups  xmm1, xmmword ptr [rdx + 12]
        shufps  xmm5, xmm5, 0
        mulps   xmm5, xmm4
        shufps  xmm6, xmm6, 0
        mulps   xmm6, xmm3
        addps   xmm6, xmm5
        movups  xmm5, xmmword ptr [rdx + 16]
        shufps  xmm7, xmm7, 0
        mulps   xmm7, xmm2
        addps   xmm7, xmm6
        movups  xmm6, xmmword ptr [rdx + 20]
        shufps  xmm1, xmm1, 0
        mulps   xmm1, xmm8
        addps   xmm1, xmm7
        movups  xmm7, xmmword ptr [rdx + 24]
        shufps  xmm5, xmm5, 0
//....
```
where the memory-to-register `movups` before `shufps` makes perfect sense.

**Comment by calebzulawski** [comment]
I believe this is correct behavior--if you look at `shufps` the first register is actually both an input and an output.  The `shufps` in this case is splatting from a particular lane.  In some cases the `mov` is elided because the splat is performed into the source register, but in the scenario where it's splat into a new register, the `mov` is necessary to copy the data.  For example,

```
movaps  xmm0, xmm5
shufps  xmm0, xmm5, 0
```

might be more easily understood as this equivalent:

```
movaps  xmm0, xmm5
shufps  xmm0, xmm0, 0
```

The `mov` is necessary to write to `xmm0` without overwriting `xmm5`.

**Comment by calebzulawski** [comment]
One thing I'm not sure of is why it's writing to occupied registers rather than using more registers (only up to xmm9 is used).  Using more registers should allow it to skip the `mov`s.

**Comment by ZhennanWu** [comment]
> I believe this is correct behavior--if you look at `shufps` the first register is actually both an input and an output. The `shufps` in this case is splatting from a particular lane. In some cases the `mov` is elided because the splat is performed into the source register, but in the scenario where it's splat into a new register, the `mov` is necessary to copy the data. For example,
> 
> ```
> movaps  xmm0, xmm5
> shufps  xmm0, xmm5, 0
> ```
> 
> might be more easily understood as this equivalent:
> 
> ```
> movaps  xmm0, xmm5
> shufps  xmm0, xmm0, 0 # note the different source register
> ```
> 
> The `mov` is necessary to write to `xmm0` without overwriting `xmm5`.

Ah, I see where I made the mistake. I mixed up `shufps` with [`permilps`](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=permute&ig_expand=5220). With permute, there would be no need to do the move. But permute is under `avx` which is not available for `x86-64-v2`. Thank you!
