### ISSUE TITLE
Make sure we don't miss any other trait methods that people expect to be lanewise instead

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/portable-simd#257]
we currently have min/max (#247) and clamp (#253) that are missing from Simd for integers, we should go through all the trait methods for std traits implemented by Simd and Mask and ensure that users get the appropriate lanewise version where expected.

incomplete list (edit as needed):

## Integers
- [x] Ord::min
- [x] Ord::max
- [x] Ord::clamp
- [x] PartialEq::eq
- [x] PartialEq::ne
...

## Masks
- [x] Ord::min
- [x] Ord::max
- [x] Ord::clamp
- [x] PartialEq::eq
- [x] PartialEq::ne
...

**Comment by scottmcm** [comment]
I'll note that LLVM has vector intrinsics for integer min/max now: https://llvm.org/docs/LangRef.html#llvm-smax-intrinsic

**Comment by RalfJung** [comment]
Why is `Ord::clamp` not on the list for masks?

**Comment by Lokathor** [comment]
masks are effectively a list of bools, doesn't make sense to clamp them really.

**Comment by programmerjake** [comment]
> Why is `Ord::clamp` not on the list for masks?

because the list is whatever stuff i felt like adding at the time...it still needs to be filled out.

**Comment by RalfJung** [comment]
> masks are effectively a list of bools, doesn't make sense to clamp them really.

That would be an argument for not having `m.clamp` in the first place. But that is impossible if they implement `Ord`.
The question is just whether clamp works lexicographically or lanewise.

**Comment by workingjubilee** [comment]
I made the list formatted nice and I left clamp out because my brain failed to parse what clamp even does on, yes, a "vector of bools".

**Comment by RalfJung** [comment]
clamp is defined the moment max and min are defined, so if you can imagine max and min on bools then just derive clamp from that. ;)
```rust
fn clamp(self, lo, up) { self.max(lo).min(up) }
```
I think it would be a mistake to overload `max` and `min` but not also `clamp`, as that would violate the above definition that should always hold.

**Comment by calebzulawski** [comment]
This is now done via the `SimdPartialOrd`, `SimdOrd`, and `SimdPartialEq` traits, which are implemented on both regular vectors and masks (added in #265).
