### ISSUE TITLE
swizzle for Mask

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/portable-simd#268]
I just noticed `Mask` is missing `swizzle`.

**Comment by calebzulawski** [comment]
Yep, I think we were aware with the original PR and decided we'd deal with it later.  Bitmasks complicate it a bit.

**Comment by workingjubilee** [comment]
Is there a practical use-case being facilitated here? I believe, fwiw, I just wanna know.

**Comment by programmerjake** [comment]
IIRC I needed it when trying to make some example code on godbolt.org to answer someone's question on Zulip, unfortunately I can't find it right now. IIRC I needed to use int vector swizzle to work around the lack of mask swizzling
