### ISSUE TITLE
Semantics of simd_select_bitmask for "out-of-bounds" mask?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/portable-simd#269]
What should the semantics of the `simd_select_bitmask` intrinsic be when the bitmask has "out-of-bounds" bit set? This can happen when the vector length is less than 8, and the bitmask is stored as a `u8`.

- This could be just declared UB, so codegen does not have to worry about this case. That's what https://github.com/rust-lang/miri/pull/2029 implements for Miri. However, then [this](https://github.com/rust-lang/portable-simd/blob/72df4c45056a8bc0d1b3f06fdc828722177f0763/crates/core_simd/src/masks/full_masks.rs#L161) is unsound, as a user can pass an arbitrary `u8` to that function. So, we'd have to mask out the extra bits before passing them to `simd_select_bitmask`.
- Or we could just say that these extra bits are ignored, and then codegen backends will have to make sure they handle that case properly.

The portable-simd test suite currently does not hit this case at all.

**Comment by calebzulawski** [comment]
I believe it's not UB in the current LLVM backend, but I'm not sure if that was intentional.

**Comment by RalfJung** [comment]
Yeah, the current backend does [`trunc`](https://github.com/rust-lang/rust/blob/4f008e06c33e1ef729bce839c0899154e71902b0/compiler/rustc_codegen_llvm/src/intrinsic.rs#L889).

However, @workingjubilee mentioned future plans for other bitmask-taking intrinsics where this would be UB, so it might make sense to make it UB here as well.

**Comment by workingjubilee** [comment]
Yes, specifically I was thinking about possibly executing masked loads with a bitvector. We could require it to implicitly trunc to the right size but it seems simpler in terms of codegen to just say the bitvector should probably specify reading the exact number of values you want, even if read as a larger number. That way if you just slam the number into a register and do the masked load, it always works correctly.

**Comment by RalfJung** [comment]
The docs for the intrinsic also explicitly say "padding bits must be all zero", so I think currently, this has a very clear answer -- out-of-bounds masks are UB.

If there's a motivation to change that, someone should file an issue spelling that out. :)
