### ISSUE TITLE
`scatter` and `gather` are not strict provenance compatible

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/portable-simd#271]
The implementations of `gather` and `scatter` in portable-simd currently are not compatible with [strict provenance](https://github.com/rust-lang/rust/issues/95228). Specifically, it is [`SimdConstPtr::wrapping_add`](https://github.com/rust-lang/portable-simd/blob/dddfffcfb3e49c752d6a28039735ada2552d0307/crates/core_simd/src/vector/ptr.rs#L23) that **transmutes** a vector of pointers to a vector of integers, does integer arithmetic, and then transmutes back the result. It also has safety comments that are somewhat in conflict with what I am writing in https://github.com/rust-lang/rust/pull/95547. ;)

**Comment by calebzulawski** [comment]
I think this is easy to fix, we just need a new intrinsic for vector pointer offset

**Comment by RalfJung** [comment]
So how would one start fixing this? Add a new `simd_offset` case [around here](https://github.com/rust-lang/rust/blob/d32ce37a171663048a4c4a536803434e40f52bd6/compiler/rustc_codegen_llvm/src/intrinsic.rs#L1808)? Can I just call `bx.inbounds_gep` with SIMD types?

**Comment by calebzulawski** [comment]
Yeah, that seems right to me.  It might also be possible to implement it in `rustc_codegen_ssa`?

**Comment by RalfJung** [comment]
>  It might also be possible to implement it in rustc_codegen_ssa?

Are there other SIMD intrinsics that do that that could be used as a template?

**Comment by calebzulawski** [comment]
Hmm, I was thinking offsetting pointers is pretty backend-agnostic but I don't see anything similar.  It's probably fine putting it in the LLVM backend with all of the other SIMD intrinsics.
