### ISSUE TITLE
Divide and Rem is very slow

### ISSUE THREAD

**Issue by YjyJeff** [rust-lang/portable-simd#285]
I found divide(/) and rem(%) operation is very slow. Blew is my benchmark code:
```
fn modulo_plain(c: &mut Criterion) {
    let data = (0..1024_u64).collect::<Vec<_>>();
    let mut result = vec![0_u64; 1024];
    c.bench_function("naive modulo", |b| {
        b.iter(|| {
            result
                .iter_mut()
                .zip(data.iter())
                .for_each(|(a, b)| *a = *b % 3);
        })
    });

    c.bench_function("simd modulo", |b| {
        b.iter(|| {
            let chunks = data.chunks_exact(8);
            let result_chunks = result.chunks_exact_mut(8);
            let scalar = std::simd::u64x8::splat(3);
            chunks.zip(result_chunks).for_each(|(chunk, result)| {
                let v = std::simd::u64x8::from_slice(chunk) % scalar;
                result
                    .iter_mut()
                    .zip(v.as_array())
                    .for_each(|(r, v)| *r = *v);
            });
        });
    });
}

criterion_group!(benches, modulo_plain);
criterion_main!(benches);
```

The simd_modulo is much slower than naive modulo, and replace the `%` operation with `/` will get the same result. If you replace it with `+`, it will be much faster than naive version. What's wrong with it? 

I am using `Intel(R) Xeon(R) Platinum 8255C CPU`, it supports avx512. I run the bench with the following command: 
```
RUSTFLAGS='-C target-cpu=native' cargo bench
```

**Comment by calebzulawski** [comment]
Most CPUs (including yours) don't have integer division vector instructions.  In that case, division is performed by looping across each element in the vector.  In your particular benchmark, you are likely seeing the overhead from chunking the Iterator.

**Comment by YjyJeff** [comment]
> Most CPUs (including yours) don't have integer division vector instructions. In that case, division is performed by looping across each element in the vector. In your particular benchmark, you are likely seeing the overhead from chunking the Iterator.

Got it, thanks!
