### ISSUE TITLE
Arbitrary bitselect

### ISSUE THREAD

**Issue by Phosra** [rust-lang/portable-simd#291]
I would like to request that the `std::simd` API offer a ternary function for vectorized bit selection between three vectors, none of which must necessarily be a `std::simd::Mask`.

Given that I believe that this makes the most sense being offered for `Simd<u32, N>`, as it is the result of `to_bits`/`from_bits`, such function should be the equivalent to the following:
```rust
use std::simd::Simd;

#[inline(always)]
const fn bit_select<const N: usize>(
 false_vector: Simd<u32, N>,
 true_vector: Simd<u32, N>,
 selection_mask: Simd<u32, N>
) -> Simd<u32, N> {
 ((false_vector ^ true_vector) & selection_mask) ^ false_vector
}
```

This gives the bit from a vector chosen by the mask:
\- if the mask bit is `0`: give the bit from `false_vector`
\- if the mask bit is `1`:  give the bit from `true_vector`
(note: elements/bytes are not being selected - bits are)

Some ISAs offer a direct instruction for this, e.g., ARM's NEON offers `vbsl`, and WebAssembly fixed-width SIMD offers `bitselect`.

When searching for this, I had thought that this was requested/implemented in #114, yet that seemed to have been specifically involving `std::simd::Mask` (full true/false), as opposed to arbitrary and mixed-bit positions. This API allows implementing operations like `copysign`, whereas the other cannot.

Finally, I believe that this should directly map to an LLVM `vselect`, and/or may use the same intrinsic used for `std::simd::Mask::select`.

**Comment by workingjubilee** [comment]
...vselect? You mean select on a vector? That requires
> The ‘select’ instruction requires an ‘i1’ value or a vector of ‘i1’ values indicating the condition, and two values of the same [first class](https://llvm.org/docs/LangRef.html#t-firstclass) type.

which is what our Mask type is intended to correspond to. 1 bit per element:
> If the condition is a vector of i1, then the value arguments must be vectors of the same size, and the selection is done element by element.

LLVM generates the following code for `aarch64-unknown-linux-gnu` with a vector length of 4:
```asm
example::bit_select:
        .cfi_startproc
        ldr     q0, [x1]
        ldr     q1, [x0]
        ldr     q2, [x2]
        bif     v0.16b, v1.16b, v2.16b
        str     q0, [x8]
        ret
```

Challenging it to lower a slightly harder vector length, like 16, gives us the instruction you're looking for:
```asm
example::bit_select:
        .cfi_startproc
        ldp     q5, q0, [x1, #32]
        ldp     q2, q1, [x0, #32]
        ldp     q17, q16, [x2, #32]
        bit     v2.16b, v5.16b, v17.16b
        ldp     q4, q3, [x0]
        bif     v0.16b, v1.16b, v16.16b
        stp     q2, q0, [x8, #32]
        ldp     q7, q6, [x1]
        ldp     q1, q18, [x2]
        bsl     v1.16b, v7.16b, v4.16b
        bit     v3.16b, v6.16b, v18.16b
        stp     q1, q3, [x8]
        ret
```

For wasm, the codegen is much worse, even for the 4-lane version:
```wasm
example::bit_select:
        .functype       example::bit_select (i32, i32, i32, i32) -> ()
        .local          v128
        local.get       0
        local.get       2
        v128.load       0
        local.get       1
        v128.load       0
        local.tee       4
        v128.xor
        local.get       3
        v128.load       0
        v128.and
        local.get       4
        v128.xor
        v128.store      0
        end_function
```

For the wasm-specific one, it's much better:
```rust
pub fn wasm_bit_select(f: wasm32::v128, t: wasm32::v128, s: wasm32::v128) -> wasm32::v128 {
    wasm32::v128_bitselect(f, t, s)
}
```

```wasm
example::wasm_bit_select:
        .functype       example::wasm_bit_select (i32, i32, i32, i32) -> ()
        local.get       0
        local.get       1
        v128.load       0
        local.get       2
        v128.load       0
        local.get       3
        v128.load       0
        v128.bitselect
        v128.store      0
        end_function
```

It seems like a bug in LLVM that it's not recognizing the pattern and lowering to bitselect.

**Comment by Phosra** [comment]
> ...vselect? You mean select on a vector? That requires
> 
> > The ‘select’ instruction requires an ‘i1’ value or a vector of ‘i1’ values indicating the condition, and two values of the same [first class](https://llvm.org/docs/LangRef.html#t-firstclass) type.
> 
> which is what our Mask type is intended to correspond to. 1 bit per element:
> 
> > If the condition is a vector of i1, then the value arguments must be vectors of the same size, and the selection is done element by element.

Hmm... I'm... not certain? that sounds like `select <N x i1> %c, <N x T> %x, <N x T> %y`, which afaik is the current `std::simd::Mask::select`, because each element is ≈ `i8`. (Correct me if I'm wrong!)
Now, I may have been wrong about `vselect` (I've forgotten where I encountered it previously), and it seems that it is just as you described, `select` accepting vector operands.
So, it seems that I was in err! I'm not sure what this maps to in LLVM, if anything at all.

> Tinkering with the following [Godbolt](https://rust.godbolt.org/z/P3MbT4bb9)... LLVM generates the following code for `aarch64-unknown-linux-gnu` with a vector length of 4:
> 
> ```assembly
> example::bit_select:
>         .cfi_startproc
>         ldr     q0, [x1]
>         ldr     q1, [x0]
>         ldr     q2, [x2]
>         bif     v0.16b, v1.16b, v2.16b
>         str     q0, [x8]
>         ret
> ```

Wait, this is good! NEON has three related instructions for bitwise insertion based on a mask: [vbit, vbif, and vbsl](https://developer.arm.com/documentation/dui0489/c/neon-and-vfp-programming/neon-logical-and-compare-operations/vbif--vbit--and-vbsl?lang=en). Essentially, LLVM is doing it's job here.

> Challenging it to lower a slightly harder vector length, like 16, gives us the instruction you're looking for:
> 
> ```assembly
> example::bit_select:
>         .cfi_startproc
>         ldp     q5, q0, [x1, #32]
>         ldp     q2, q1, [x0, #32]
>         ldp     q17, q16, [x2, #32]
>         bit     v2.16b, v5.16b, v17.16b
>         ldp     q4, q3, [x0]
>         bif     v0.16b, v1.16b, v16.16b
>         stp     q2, q0, [x8, #32]
>         ldp     q7, q6, [x1]
>         ldp     q1, q18, [x2]
>         bsl     v1.16b, v7.16b, v4.16b
>         bit     v3.16b, v6.16b, v18.16b
>         stp     q1, q3, [x8]
>         ret
> ```

:+1:

> For wasm, the codegen is much worse, even for the 4-lane version:
> 
> ```webassembly
> example::bit_select:
>         .functype       example::bit_select (i32, i32, i32, i32) -> ()
>         .local          v128
>         local.get       0
>         local.get       2
>         v128.load       0
>         local.get       1
>         v128.load       0
>         local.tee       4
>         v128.xor
>         local.get       3
>         v128.load       0
>         v128.and
>         local.get       4
>         v128.xor
>         v128.store      0
>         end_function
> ```
> 
> For the wasm-specific one, it's much better:
> 
> ```rust
> pub fn wasm_bit_select(f: wasm32::v128, t: wasm32::v128, s: wasm32::v128) -> wasm32::v128 {
>     wasm32::v128_bitselect(f, t, s)
> }
> ```
> 
> ```webassembly
> example::wasm_bit_select:
>         .functype       example::wasm_bit_select (i32, i32, i32, i32) -> ()
>         local.get       0
>         local.get       1
>         v128.load       0
>         local.get       2
>         v128.load       0
>         local.get       3
>         v128.load       0
>         v128.bitselect
>         v128.store      0
>         end_function
> ```
> 
> It seems like a bug in LLVM that it's not recognizing the pattern and lowering to bitselect.

Ouch! Quite possible, the usage of the appropriate equivalent instructions in ARM does indicate that LLVM is capable of understanding what this pattern is doing, and that optimisation can be worked out asynchronously with LLVM. (I'll search through the llvm-project and possibly open an issue soon.)

Nonetheless, I'm most interested in knowing what the team here thinks of inclusion/exclusion of the instruction? I cannot estimate usage, but I believe that the inclusion in ARM and Wasm may give an estimate as to how often compilers and programmers may need to make use of it, but that doesn't drive the decisions here anyways.

**Comment by workingjubilee** [comment]
Ah, I may have already opened an issue: https://github.com/llvm/llvm-project/issues/56827

**Comment by workingjubilee** [comment]
> Nonetheless, I'm most interested in knowing what the team here thinks of inclusion/exclusion of the operation? I cannot estimate usage, but I believe that the inclusion in ARM and Wasm may give an estimate as to how often compilers and programmers may need to make use of it, but that doesn't drive the decisions here anyways.

"Do machines offer an instruction for it?" is not quite the deciding element for us, and there's a plethora of various logical bit-manipulation operations that we could hypothetically add explicit support for. However, given that LLVM successfully appropriately pattern-matches sets of LLVMIR ands, ors, and xors into these forms for backends... well, most backends... and we don't have an architecture-neutral LLVMIR instruction for it, I am somewhat loathe to add them. When adding something that the primitive types don't have, the question I have is "is this vector-specific?" And bitselect kinda isn't.

**Comment by Phosra** [comment]
Fair enough, thank you for the response (and for the LLVM report). Feel free to close this as you see fit.

**Comment by workingjubilee** [comment]
tbh, if you decided to persuade LLVM to add it to their IR, given that [Cranelift supports it for obvious reasons](https://docs.rs/cranelift-codegen/latest/cranelift_codegen/ir/trait.InstBuilder.html#method.bitselect), and I dunno, I wouldn't be surprised if GCC does too, it might be an easy pitch to add it. We might still want to have a scalar equivalent in rustc first, tho'.

**Comment by Phosra** [comment]
Well, it makes sense to just leave that that to compiler optimisations. Assuming that the programmer can construct (or lookup) a pattern* that maps to "bit selection," that the compiler can optimise, then it does indeed seem unnecessary. It's definitely not in the same class as element swizzling and such.

\* And I do really expect that this wouldn't be of significant difficulty for users.

Although... it really it does seem too similar to the existing `simd::Mask::select`, and `Mask::select` can be implemented in terms of this, but not the other way around.

> We might still want to have a scalar equivalent in rustc first, tho'.

Given that the Rust standard library is intended to be small, and exclude simple conveniences such as this, I have much doubt that it could make it though, and that it would be worth its weight.

I'll take the liberty of closing this for now though.
