### ISSUE TITLE
Conversion from arch types

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/portable-simd#296]
Currently, it is possible to convert from portable_simd vectors to core::arch vectors, but not the reverse. Given that the vector element types that I have seen so far have no invalid bit patterns, I would expect that operation to always be safe. Am I misunderstood ?

**Comment by TheIronBorn** [comment]
at least for x86 there exists `impl From<u8x16> for __m128i`

**Comment by HadrienG2** [comment]
Yes, this direction already exists, it is the reverse direction that does not exist yet.

**Comment by calebzulawski** [comment]
Pretty sure this existed in the past and got lost at some point.  Vaguely related to #187.

**Comment by TheIronBorn** [comment]
Sorry, I meant [`impl From<__m128i> for u8x16`](https://doc.rust-lang.org/core/arch/x86/struct.__m128i.html#impl-From%3C__m128i%3E) which also exists

**Comment by HadrienG2** [comment]
Ah, yes, you're right, sorry, I wonder how I managed to miss them.

**Comment by HadrienG2** [comment]
Looking further, I see how. The From impl appears on the doc page of the arch types, but not on that of the Simd type.

What is strange is that you see both From impls on the doc page of the arch type. I wonder if rustdoc could be somehow massaged into displaying both From impls on the doc of the Simd type too...
