### ISSUE TITLE
Trait "From<Mask<T, LANES>> for Simd<T, LANES>" is currently not implemented

### ISSUE THREAD

**Issue by AHK66** [rust-lang/portable-simd#305]
The code segment
```rust
let m = Mask::<i8, 16>::splat(true);
let s = Simd::<i8, 16>::from(m);
```
currently triggers the error message:
"the trait bound `std::simd::Simd<i8, 16>: From<std::simd::Mask<i8, 16>>` is not satisfied" 

Reason:
Momentarily, "From<Mask<T, LANES>> for Simd<T, LANES>" is implemented for _core::core_simd::masks::mask_impl::Mask<T, LANES>>_(in file _full_masks.rs_) but not for _core::core_simd::masks::Mask<T, LANES>>_ (in file _masks.rs_).

Possible Fix:
In  _masks.rs_ add the below additional implementation for the trait _From_:

```rust
impl<T, const LANES: usize> From<Mask<T, LANES>> for Simd<T, LANES>
where
    T: MaskElement,
    LaneCount<LANES>: SupportedLaneCount,
{
    #[inline]   
    fn from(value: Mask<T, LANES>) -> Simd<T, LANES> {
        mask_impl::Mask::into(value.0)
    } 
}
```

Best wishes
AHK66

**Comment by calebzulawski** [comment]
I think we intentionally do not implement `From` for masks to vectors.  You can perform this conversion with [to_int](https://doc.rust-lang.org/std/simd/struct.Mask.html#method.to_int)

**Comment by AHK66** [comment]
Oh, sorry, I was so fixed on the From-trait that I missed the to_int function. 
Thank you for the feedback!

Best wishes
AHK66
