### ISSUE TITLE
Mask::test/test_unchecked not getting fully inlined

### ISSUE THREAD

**Issue by jhorstmann** [rust-lang/portable-simd#308]
I have the following code as the last step in a vectorized aggregation function (number of lanes reduced to simplify the assembly output):

```rust
#![feature(portable_simd)]

use std::simd::*;

pub fn reduce_sum_masked(v: i64x2, m: mask64x2) -> i64 {
    let array = v.to_array();
    array
        .iter()
        .enumerate()
        .filter(|(i, _)| unsafe { m.test_unchecked(*i) })
        .map(|(_, x)| *x)
        .sum()
}
```

When compiled with `-Copt-level=3 -Ctarget-cpu=skylake` I see the following pattern in the generated assembly:

```asm
mov     r12, qword ptr [rip + core::core_simd::masks::<impl core::core_simd::masks::sealed::Sealed for i64>::eq@GOTPCREL]
...
call    r12
...
call    r12
test    al, al
...
```

For each lane there is a function call that is not getting inlined.

The solution might just be a missing `#[inline]` annotation somewhere, in that case I'd be happy to provide a PR.

### Meta

[Example in the compiler explorer](https://rust.godbolt.org/z/GovhEfjsK)

**Comment by programmerjake** [comment]
not that this fixes that inlining issue, you should use explicitly simd operations if you want simd output, not immediately convert the input to an array and use all the standard scalar iterator stuff.

much more optimized variant:
https://rust.godbolt.org/z/j4KTcq9he

**Comment by calebzulawski** [comment]
Agreed with @programmerjake, there is a better way to implement that particular function.  As far as the inlining goes, there were a few functions missing the attribute, which I've fixed in the referenced PR.

**Comment by jhorstmann** [comment]
Agree for the `sum` aggregation. For more complex aggregations (for example postgres min/max consideres NaN to be bigger than any non-NaN number) it seemed useful to store into a temporary in order to reuse the already existing scalar remainder code.

Thanks for the quick response and PR!
