### ISSUE TITLE
explicit simd store -- opposite of Simd::from_slice

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/portable-simd#324]
currently we have to either cast the dest pointer to `Simd<T, N>` and use `write_unaligned` or use an array-typed store, this is somewhat likely to cause issues at some point. plus, having a function on `Simd` is nicer than having to figure out to use `*dest = *val.as_array()`.

**Comment by calebzulawski** [comment]
There is also `slice.copy_from_slice(vector.as_slice())`.

**Comment by programmerjake** [comment]
> There is also `slice.copy_from_slice(vector.as_slice())`.

yes, but that also isn't a vector store, it's basically an array store again.
