### ISSUE TITLE
Missing Neg for unsigned types

### ISSUE THREAD

**Issue by dhardy** [rust-lang/portable-simd#330]
`Simd` misses impls of `Neg` for unsigned integer types.

Since `Simd` uses wrapping arithmetic, negation for unsigned values has a good definition: `N - val % N` where `N = MAX + 1`. See e.g. [`u8::wrapping_neg`](https://doc.rust-lang.org/stable/std/primitive.u8.html#method.wrapping_neg).

And, yes, I want to use this (calculation of rejection threshold for Lemire's method of sampling unbiased integers uniformly from a range).

**Comment by Lokathor** [comment]
I've needed this exact thing myself in scalar code before.

**Comment by Unlikus** [comment]
yes, but `Neg` is implicit. Someone might write `-` with the intention of negating the sign.
In normal Rust the wrapping behavior is very explicit, which prevents these sort of bugs.

**Comment by dhardy** [comment]
Let me repeat myself: all arithmetic on [`Simd`] is explicitly wrapping. It's right there in the docs. You can get wrapping behaviour from just adding two `Simd` numbers together.

If you want protection against unintentional wrapping, I suggest you use normal integer types, not `Simd`. (Auto-vectorisation can still get you some of the speed-ups of SIMD operations.)

If you really think `Simd` should not have implicit wrapping behaviour, open a new issue; that has almost nothing to do with this one.

**Comment by Unlikus** [comment]
I am not arguing that [`Simd`] unsinged intergers should not be wrapping.
I argue that the unary "- operator" should not be implemented. This operator implies a change of sign, which would not be the case here. There is a reason a lot of linters will flag this in C and C++ code (where the unary minus is defined for unsigned types), see https://rules.sonarsource.com/c/RSPEC-876

Instead an explicit `wrapping_neg` function like normal Rust unsigned types are preferable in my opinion.

**Comment by workingjubilee** [comment]
Both conciseness and aligning the Simd types with the intuitions lended by their scalar variants is important to us, so it's not immediately clear which we should do here. I agree that implementing Neg is a footgun, but I don't like adding functions named "`wrapping_`" because the types are, well, already wrapping, and we should stand firm on that. It's only different in the pointer case due to "the pointer API is kinda weird, and wrapping doesn't mean the same thing there".
