### ISSUE TITLE
`cast_ptr` is willing to cast between mut and non-mut pointers

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/portable-simd#349]
I would expect the following code not to compile:
```rust
    let _val: Simd<*mut u8, 4> = Simd::<*const i32, 4>::splat(ptr::null()).cast_ptr();
```
This matches the `cast` method on scalar raw pointers, which also only changes the pointee type, never mutability. Changing mutability requires an `as` cast, or a `cast_mut`/`cast_const`.

But it looks like its SIMD equivalent will happily swap between `const` and `mut` as needed.

**Comment by calebzulawski** [comment]
`cast_ptr` was designed to do everything that `as` can do, but maybe this isn't a good idea.

**Comment by RalfJung** [comment]
Then why is `cast_ptr` separate from `cast`?

**Comment by calebzulawski** [comment]
I think we thought to make it slightly safer than `as`. But it probably makes more sense for `cast_ptr` to mirror `ptr::cast` and not allow changing mutability.
