### ISSUE TITLE
Looking for "blend" methods.

### ISSUE THREAD

**Issue by RazrFalcon** [rust-lang/portable-simd#352]
Aka `_mm256_blendv_ps`, `_mm_blendv_ps`, `vbslq_u32` and `v128_bitselect`.

Are they implemented already and I simply haven't found them? Are they planned at all? Maybe I can use something else in the meantime?

**Comment by RazrFalcon** [comment]
I guess I was looking for [Mask::select](https://doc.rust-lang.org/stable/std/simd/struct.Mask.html#method.select).

**Comment by calebzulawski** [comment]
Yep, I believe select does what you're looking for.
