### ISSUE TITLE
Move intrinsic declarations to core and verify behavior

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/portable-simd#381]
The intrinsics should exist in core, which will make them easier to test and document.  There is currently no single set of documentation explaining the semantics of the intrinsics, so this module would serve as the "definitive" description.

Additionally, we should ensure that the semantics match the documentation and is sound.

**Comment by RalfJung** [comment]
> Additionally, we should ensure that the semantics match the documentation and is sound.

Note that there are two semantics:
- the codegen backend, which "just" has to generate correct behavior whenever the safety requirements are met
- Miri, which also has to check whether the safety requirements are actually met
