### ISSUE TITLE
Support for ARM Helium SIMD instructions

### ISSUE THREAD

**Issue by michael-p** [rust-lang/portable-simd#442]
[ARM Helium](https://www.arm.com/technologies/helium) is a SIMD instruction set extension for Cortex-M microcontrollers, currently the Cortex-M55 and Cortex-M85, with 128-bit width. It is already supported by LLVM (intrinsics and auto-vectorization). Will it be possible to use it with the portable SIMD API as well?
Thanks!

**Comment by programmerjake** [comment]
it already works for most of the operations that don't use architecture-specific intrinsics: https://rust.godbolt.org/z/TxoGKv777

**Comment by michael-p** [comment]
Thanks, I'll close this issue and open more specific issues in case I encounter missing architecture-specific stuff.
