### ISSUE TITLE
Failing wasm tests

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/portable-simd#92]
I tracked down the cause of the wasm test failures and it looks like it's due to the comparison ops added to tests in #80.  It looks like wasmparser has been updated to support these opcodes so it's just a matter of the changes propagating to wasm-bindgen-test.  I opened rustwasm/wasm-bindgen#2522 to track this.

I think we can just ignore the failures for now and they should start passing against once wasm-bindgen-test is updated.

cc @workingjubilee

**Comment by workingjubilee** [comment]
I would _like_ to find all the wasm tests that are currently failing on Chrome and disable them individually, but that might be asking too much.

**Comment by workingjubilee** [comment]
This currently hinges on https://github.com/rustwasm/wasm-pack/issues/998
To fix this we can either update our tests to no longer depend on using the `wasm-pack` binary, or wait.
I opened #96 to temporarily omit the tests in the meanwhile.

**Comment by workingjubilee** [comment]
This _actually_ was waiting for `wasm-bindgen-cli` to do an actual release, as it turns out. As Travis is broken, I will move the relevant wasm CI to GHA when I patch the tests back in and force an appropriate minimal `wasm-bindgen` version.
